### ISSUE TITLE
Create a tag

### ISSUE THREAD

**Issue by shawnsparks** [MarvAmBass/docker-nginx-registry-proxy#1]
Glad somebody has this image out there. Mind creating a v1.0.0 tag so it's easy to know as a consumer I'm always pulling the same image?

**Comment by MarvAmBass** [comment]
Hi Marshmellow,

I could, but actually I've some concerns about it.

If I'd tag the Image, this would freeze the state of the nginx. So if you and others are still using the image in 2 years it will work, but there is a high chance of being exploitable.

I try to allways use latest stuff with my Images. So for example: 

You have a running and working marvambass/nginx-registry-proxy you can tag it yourself locally.
Two months later you pull a new version of my latest image and test if it works. If so you use the new one - if not you open a new ticket here, and i try to fix it.

You have to keep in mind, this images comes with an included reverse proxy with htaccess and ssl - its intended for direct internet connections. In my opinion you should never use a old version of a online service (just because it works) better fix the applications to get it run with the newer version.

unfortunatly there are no unit testing frameworks for docker out there, which would ensure a special functionality

if you use my latest image, you should be safe, I allways try to keep everything working and updated.

**Comment by MarvAmBass** [comment]
if you need tags, fork this project
